import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:smriti/core/local_db/alert_store.dart';
import 'package:smriti/core/local_db/local_store.dart';
import 'package:smriti/core/models/alert.dart';
import 'package:smriti/core/models/caregiver.dart';
import 'package:smriti/core/models/reminder.dart';
import 'package:smriti/modules/asha/data/asha_repository.dart';
// Reusing the Patient module's DailyLivingPrompt shape (not its LocalStore) for the
// goals a caregiver sets — see addGoal's doc comment for why the two sides don't
// share storage yet.
import 'package:smriti/modules/patient/models/patient_models.dart' show DailyLivingPrompt;

class ReminderAdherence {
  final Reminder reminder;
  final int acknowledged;
  final int missed;

  const ReminderAdherence({required this.reminder, required this.acknowledged, required this.missed});

  int get total => acknowledged + missed;

  /// An untouched reminder is not "100% adhered" — it has no signal yet. Callers should
  /// check [hasData] before presenting [rate] as an achievement.
  bool get hasData => total > 0;

  double get rate => total == 0 ? 1.0 : acknowledged / total;
}

/// Ack rate for one reminder category, which is the granularity the caregiver spec asks
/// the dashboard to surface ("ack rate per reminder type").
class TypeAdherence {
  final ReminderType type;
  final int acknowledged;
  final int missed;

  const TypeAdherence({required this.type, required this.acknowledged, required this.missed});

  int get total => acknowledged + missed;
  bool get hasData => total > 0;
  double get rate => total == 0 ? 1.0 : acknowledged / total;
}

class WeeklyDigest {
  final int sessionsAttended;
  final int sessionsMissed;
  final double overallAdherenceRate;
  final bool hasAdherenceData;
  final List<String> highlights;

  const WeeklyDigest({
    required this.sessionsAttended,
    required this.sessionsMissed,
    required this.overallAdherenceRate,
    required this.hasAdherenceData,
    required this.highlights,
  });

  int get sessionsScheduled => sessionsAttended + sessionsMissed;
}

/// Local-first repository for the Caregiver module. Persists via [LocalStore]
/// (shared_preferences today, standing in for sqflite — see that class) so reminders and
/// acknowledgement history survive an app restart.
///
/// Session attendance is read from [AshaRepository] rather than duplicated here: both
/// dashboards describe the same elder, and keeping two copies of "how many sessions did
/// she attend" is how they end up disagreeing.
class CaregiverRepository {
  CaregiverRepository._internal();

  static final CaregiverRepository instance = CaregiverRepository._internal();

  static const _remindersKey = 'caregiver_reminders_v2';
  static const _acksKey = 'caregiver_acks_v2';
  static const _voiceClipsKey = 'caregiver_voice_clips_v2';
  static const _profileKey = 'caregiver_profile_v2';
  static const _goalsKey = 'caregiver_goals_v1';

  final List<Reminder> _reminders = [];
  final List<ReminderAck> _acks = [];
  final List<String> _voiceClips = [];
  final List<DailyLivingPrompt> _goals = [];

  CaregiverProfile _profile = const CaregiverProfile(
    id: 'caregiver-demo-1',
    name: 'Imlong Ao',
    kind: CaregiverKind.family,
    patientId: 'p1',
  );

  bool _loaded = false;

  final _changes = StreamController<void>.broadcast();
  Stream<void> get onChange => _changes.stream;

  List<Reminder> get reminders => List.unmodifiable(_reminders);

  /// Daily-living-style goals the caregiver sets herself — "make tea", "go to the
  /// bathroom at night", that kind of single-step routine nudge — as opposed to
  /// [reminders], which are scheduled medicine/hydration/appointment alerts.
  List<DailyLivingPrompt> get goals => List.unmodifiable(_goals);

  CaregiverProfile get profile => _profile;

  /// Alerts live in the shared [AlertStore] because the ASHA module raises them.
  List<AlertItem> get alerts => AlertStore.instance.all;

  /// Recorded clips available to reuse across reminders (novelty claim #6: "record once,
  /// reuse across reminders") instead of re-recording each time.
  List<String> get voiceClips => List.unmodifiable(_voiceClips);

  Future<void> load() async {
    if (_loaded) return;
    _loaded = true;

    await AlertStore.instance.load();

    final store = LocalStore.instance;
    if (!await store.hasKey(_remindersKey)) {
      _seedDemoData();
      await _persistAll();
      // One pre-existing flag so the dashboard opens with something to act on. Flags
      // raised from here on are generated by real session scoring on the ASHA side.
      await AlertStore.instance.seedIfEmpty([
        AlertItem(
          id: 'alert-seed-1',
          patientId: _profile.patientId,
          patientName: 'Chubaimla Ao',
          message: 'Needed a hint or gave no response in 50% of her last 6 assisted rounds, '
              'against 25% at her onboarding baseline. Worth reviewing with her.',
          timestamp: DateTime.now().subtract(const Duration(hours: 6)),
        ),
      ]);
      return;
    }

    final reminderJson = await store.readList(_remindersKey);
    final ackJson = await store.readList(_acksKey);
    final voiceClipJson = await store.readList(_voiceClipsKey);
    final profileJson = await store.readList(_profileKey);
    final goalJson = await store.readList(_goalsKey);

    _reminders.addAll(reminderJson.map(Reminder.fromJson));
    _acks.addAll(ackJson.map(ReminderAck.fromJson));
    _voiceClips.addAll(voiceClipJson.map((j) => j['url'] as String));
    if (profileJson.isNotEmpty) _profile = CaregiverProfile.fromJson(profileJson.first);
    _goals.addAll(goalJson.map(DailyLivingPrompt.fromJson));
  }

  void _seedDemoData() {
    final patientId = _profile.patientId;
    final caregiverId = _profile.id;
    final now = DateTime.now();

    _reminders.addAll([
      Reminder(
        id: 'r1',
        patientId: patientId,
        createdBy: caregiverId,
        type: ReminderType.medicine,
        schedule: 'Daily 08:00, 20:00',
        textLabel: 'Take blood pressure tablet',
        voiceClipUrl: 'seed://son_medicine',
      ),
      Reminder(
        id: 'r2',
        patientId: patientId,
        createdBy: caregiverId,
        type: ReminderType.hydration,
        schedule: 'Every 3 hours',
        textLabel: 'Drink a glass of water',
      ),
      Reminder(
        id: 'r3',
        patientId: patientId,
        createdBy: caregiverId,
        type: ReminderType.appointment,
        schedule: 'Fri 11:00',
        textLabel: 'PHC follow-up visit',
      ),
      Reminder(
        id: 'r4',
        patientId: patientId,
        createdBy: caregiverId,
        type: ReminderType.activity,
        schedule: 'Daily 17:00',
        textLabel: 'Evening walk in the courtyard',
      ),
    ]);

    // Plausible ack history so the demo doesn't open on an empty dashboard.
    void seedHistory(String reminderId, int acknowledged, int missed) {
      for (var i = 0; i < acknowledged; i++) {
        _acks.add(
          ReminderAck(
            reminderId: reminderId,
            patientId: patientId,
            timestamp: now.subtract(Duration(hours: i * 6)),
            status: AckStatus.acknowledged,
          ),
        );
      }
      for (var i = 0; i < missed; i++) {
        _acks.add(
          ReminderAck(
            reminderId: reminderId,
            patientId: patientId,
            timestamp: now.subtract(Duration(hours: i * 9)),
            status: AckStatus.missed,
          ),
        );
      }
    }

    seedHistory('r1', 11, 3);
    seedHistory('r2', 18, 2);
    seedHistory('r3', 3, 1);
    seedHistory('r4', 5, 6);
  }

  // ------------------------------------------------------------------- profile

  /// The caregiver spec calls for the family/ASHA-fallback distinction to be a real
  /// field, since framing and permissions differ. Switchable here so both framings are
  /// demonstrable on one device.
  Future<void> setCaregiverKind(CaregiverKind kind) async {
    _profile = CaregiverProfile(
      id: _profile.id,
      name: kind == CaregiverKind.ashaFallback ? 'Sentimenla (ASHA)' : 'Imlong Ao',
      kind: kind,
      patientId: _profile.patientId,
      photoUrl: _profile.photoUrl,
    );
    await _persistAll();
    _changes.add(null);
  }

  // ----------------------------------------------------------------- adherence

  ReminderAdherence adherenceFor(String reminderId) {
    final reminder = _reminders.firstWhere((r) => r.id == reminderId);
    final acksForReminder = _acks.where((a) => a.reminderId == reminderId);
    return ReminderAdherence(
      reminder: reminder,
      acknowledged: acksForReminder.where((a) => a.status == AckStatus.acknowledged).length,
      missed: acksForReminder.where((a) => a.status == AckStatus.missed).length,
    );
  }

  /// Per-category ack rate, ordered worst-first so whatever needs attention is on top.
  List<TypeAdherence> adherenceByType() {
    final result = <TypeAdherence>[];
    for (final type in ReminderType.values) {
      final idsOfType = _reminders.where((r) => r.type == type).map((r) => r.id).toSet();
      if (idsOfType.isEmpty) continue;
      final acks = _acks.where((a) => idsOfType.contains(a.reminderId));
      result.add(
        TypeAdherence(
          type: type,
          acknowledged: acks.where((a) => a.status == AckStatus.acknowledged).length,
          missed: acks.where((a) => a.status == AckStatus.missed).length,
        ),
      );
    }
    result.sort((a, b) => a.rate.compareTo(b.rate));
    return result;
  }

  // ----------------------------------------------------------------- reminders

  Future<void> addReminder(Reminder reminder) async {
    _reminders.add(reminder);
    if (reminder.voiceClipUrl != null && !_voiceClips.contains(reminder.voiceClipUrl)) {
      _voiceClips.add(reminder.voiceClipUrl!);
    }
    await _persistAll();
    _changes.add(null);
  }

  Future<void> deleteReminder(String reminderId) async {
    _reminders.removeWhere((r) => r.id == reminderId);
    _acks.removeWhere((a) => a.reminderId == reminderId);
    await _persistAll();
    _changes.add(null);
  }

  /// Demo/dev stand-in for the elder-side ack arriving through the sync service, so a
  /// reminder's adherence can be driven live instead of frozen at the seed values.
  Future<void> recordAck(String reminderId, AckStatus status) async {
    final reminder = _reminders.firstWhere((r) => r.id == reminderId);
    _acks.add(
      ReminderAck(reminderId: reminderId, patientId: reminder.patientId, timestamp: DateTime.now(), status: status),
    );
    await _persistAll();
    _changes.add(null);
  }

  Future<void> markAlertReviewed(String alertId) => AlertStore.instance.markReviewed(alertId);

  // ---------------------------------------------------------------------- goals

  /// Stored on this side only for now. The Patient module reads its own, separate
  /// set of DailyLivingPrompts from its own on-device LocalStore — the two devices
  /// have no pairing/identity mechanism yet to know which patient this caregiver's
  /// goals should reach (see docs/FEATURES.md's "Not done yet" section, written
  /// while investigating the same gap for session/response-record sync). A goal
  /// added here is real and persists, but it won't show up on the elder's device
  /// until that pairing step exists.
  Future<void> addGoal({required String text, required String timeOfDay}) async {
    _goals.add(
      DailyLivingPrompt(
        id: 'goal-${DateTime.now().millisecondsSinceEpoch}',
        category: 'caregiver_set',
        triggerTimeOfDay: timeOfDay,
        text: text,
        isCaregiverCustomized: true,
      ),
    );
    await _persistAll();
    _changes.add(null);
  }

  Future<void> setGoalEnabled(String goalId, bool enabled) async {
    final index = _goals.indexWhere((g) => g.id == goalId);
    if (index == -1) return;
    _goals[index] = _goals[index].copyWith(enabled: enabled);
    await _persistAll();
    _changes.add(null);
  }

  Future<void> deleteGoal(String goalId) async {
    _goals.removeWhere((g) => g.id == goalId);
    await _persistAll();
    _changes.add(null);
  }

  // -------------------------------------------------------------------- digest

  /// Everything here is derived from real records — session attendance from the ASHA
  /// module, adherence from this module's ack history. Nothing is a fixed number.
  WeeklyDigest get weeklyDigest {
    final attendance = AshaRepository.instance.attendanceFor(_profile.patientId);

    final byType = adherenceByType();
    final totalAck = byType.fold<int>(0, (sum, a) => sum + a.acknowledged);
    final totalMissed = byType.fold<int>(0, (sum, a) => sum + a.missed);
    final total = totalAck + totalMissed;

    final openAlerts = AlertStore.instance.open.length;
    final worst = byType.where((a) => a.hasData).firstOrNull;

    return WeeklyDigest(
      sessionsAttended: attendance.attended,
      sessionsMissed: attendance.missed,
      overallAdherenceRate: total == 0 ? 1.0 : totalAck / total,
      hasAdherenceData: total > 0,
      highlights: [
        if (attendance.scheduled == 0)
          'No sessions were scheduled this week.'
        else
          'Attended ${attendance.attended} of ${attendance.scheduled} scheduled '
              'session${attendance.scheduled == 1 ? '' : 's'} this week.',
        if (worst != null)
          '${worst.type.label} reminders acknowledged ${worst.acknowledged} of ${worst.total} times '
              '(${(worst.rate * 100).round()}%).',
        if (openAlerts > 0)
          '$openAlerts trend flag${openAlerts == 1 ? '' : 's'} open — see Alerts.'
        else
          'No open trend flags this week.',
      ],
    );
  }

  Future<void> _persistAll() async {
    final store = LocalStore.instance;
    await Future.wait([
      store.writeList(_remindersKey, _reminders.map((r) => {...r.toJson(), 'id': r.id}).toList()),
      store.writeList(_acksKey, _acks.map((a) => a.toJson()).toList()),
      store.writeList(_voiceClipsKey, _voiceClips.map((url) => {'url': url}).toList()),
      store.writeList(_profileKey, [_profile.toJson()]),
      store.writeList(_goalsKey, _goals.map((g) => g.toJson()).toList()),
    ]);
  }

  /// Drops in-memory state so a test can [load] a fresh singleton against clean storage.
  @visibleForTesting
  void resetForTest() {
    _reminders.clear();
    _acks.clear();
    _voiceClips.clear();
    _goals.clear();
    _profile = const CaregiverProfile(
      id: 'caregiver-demo-1',
      name: 'Imlong Ao',
      kind: CaregiverKind.family,
      patientId: 'p1',
    );
    _loaded = false;
  }

  void dispose() => _changes.close();
}
